#### Julian Ramos

10/4/26

Homework 2

In [1]:
import pandas as pd

## Problem 1

#### 1A. Load the gun violence data set (gun-violence-data_01-2013_03-2018.csv) into a DataFrame.

In [2]:
# Load gun violence data set into a DataFrame

df = pd.read_csv('gun-violence-data_01-2013_03-2018.csv', encoding='utf-8', sep=',')

In [14]:
# use .dtypes to report data type for each column

df.dtypes

incident_id                             int64
date                           datetime64[ns]
state                                  object
city_or_county                         object
address                                object
n_killed                                int64
n_injured                               int64
incident_url                           object
source_url                             object
incident_url_fields_missing              bool
congressional_district                float64
gun_stolen                             object
gun_type                               object
incident_characteristics               object
latitude                              float64
location_description                   object
longitude                             float64
n_guns_involved                       float64
notes                                  object
participant_age                        object
participant_age_group                  object
participant_gender                     object
participant_name                       object
participant_relationship               object
participant_status                     object
participant_type                       object
sources                                object
state_house_district                  float64
state_senate_district                 float64
dtype: object

#### 1B. Filter the original data frame to show incidents that occurred in Iowa City, IA. Be sure to not include incidents that occurred in Iowa City, CA. Save results to a new data frame named iowa_city_ia. How many incidents occurred in Iowa City, IA? Show the new data frame.

In [4]:
## create new dataframe and use & operator to include IA only

iowa_city_ia = df[(df['city_or_county'] == 'Iowa City') & (df['state'] == 'Iowa')]

print(f"Incidents in Iowa City, IA: {len(iowa_city_ia)}\n")

# print the new DataFrame

print(iowa_city_ia)

Incidents in Iowa City, IA: 67

        incident_id        date state city_or_county  \
464           93491  2014-01-01  Iowa      Iowa City
1004          93495  2014-01-05  Iowa      Iowa City
8427         113057  2014-03-07  Iowa      Iowa City
11780        122662  2014-04-04  Iowa      Iowa City
14054        127527  2014-04-21  Iowa      Iowa City
...             ...         ...   ...            ...
216318       977802  2017-10-31  Iowa      Iowa City
218072       986569  2017-11-11  Iowa      Iowa City
221829      1001368  2017-12-04  Iowa      Iowa City
222739      1005517  2017-12-10  Iowa      Iowa City
225266      1015778  2017-12-27  Iowa      Iowa City

                                       address  n_killed  n_injured  \
464                   backseat of victim's car         0          1
1004                              1416 Plum St         0          0
8427                2600 block of Bartelt Road         0          1
11780                        2600 Bartelt Road         0          1
14054                        2626 Bartelt Road         0          0
...                                        ...       ...        ...
216318                        400 S Johnson St         0          0
218072                          100 S. Linn St         0          0
221829                Lakeside Dr and Amber Ln         0          0
222739  Prairie du Chien Rd NE and 320th St NE         0          1
225266                  Tracy Ln and Taylor Dr         0          0

                                             incident_url  \
464      http://www.gunviolencearchive.org/incident/93491
1004     http://www.gunviolencearchive.org/incident/93495
8427    http://www.gunviolencearchive.org/incident/113057
11780   http://www.gunviolencearchive.org/incident/122662
14054   http://www.gunviolencearchive.org/incident/127527
...                                                   ...
216318  http://www.gunviolencearchive.org/incident/977802
218072  http://www.gunviolencearchive.org/incident/986569
221829  http://www.gunviolencearchive.org/incident/100...
222739  http://www.gunviolencearchive.org/incident/100...
225266  http://www.gunviolencearchive.org/incident/101...

                                               source_url  \
464     http://thegazette.com/2014/01/06/iowa-city-pol...
1004    http://thegazette.com/2014/01/06/attempted-rob...
8427    http://www.kcrg.com/news/crime/Police-More-Tha...
11780   http://thegazette.com/2014/03/09/iowa-city-pol...
14054   http://www.kcrg.com/news/crime/Iowa-City-Polic...
...                                                   ...
216318  http://www.thegazette.com/subject/news/public-...
218072  http://www.kcrg.com/content/news/University-of...
221829  http://www.thegazette.com/subject/news/public-...
222739  http://www.thegazette.com/subject/news/public-...
225266  http://www.kwwl.com/story/37146795/2017/12/27/...

        incident_url_fields_missing  ...           participant_age  \
464                           False  ...                     1::35
1004                          False  ...                       NaN
8427                          False  ...  0:18|1:20|2:19|3:19|4:20
11780                         False  ...                       NaN
14054                         False  ...                       NaN
...                             ...  ...                       ...
216318                        False  ...                     0::19
218072                        False  ...                       NaN
221829                        False  ...       0::18||2::24||3::20
222739                        False  ...              0::11||1::13
225266                        False  ...                     0::24

                           participant_age_group  \
464                   0::Adult 18+||1::Adult 18+
1004    0::Adult 18+||1::Adult 18+||2::Adult 18+
8427                                 0:Adult 18+
11780                               0::Adult 18+
14054                                        NaN
...                                          ...
216318                              0::Adult 18+
218072                                       NaN
221829  0::Adult 18+||2::Adult 18+||3::Adult 18+
222739              0::Child 0-11||1::Teen 12-17
225266                              0::Adult 18+

                          participant_gender  \
464                     0::Female||1::Female
1004             0::Female||1::Male||2::Male
8427    0:Female|1:Male|2:Male|3:Male|4:Male
11780                              0::Female
14054                                    NaN
...                                      ...
216318                               0::Male
218072                                   NaN
221829    0::Male||1::Male||2::Male||3::Male
222739                      0::Male||1::Male
225266                               0::Male

                                         participant_name  \
464                                1::Laticia T. Robinson
1004                                                  NaN
8427    0:Denisha Davis|1:Devasier Dungtion|2:Gage Rup...
11780                                                 NaN
14054                                                 NaN
...                                                   ...
216318                                 0::Bret P Eldridge
218072                                                NaN
221829  0::Victor B Jones||1::Daivon D Jones||2::Dimio...
222739                                                NaN
225266                                   0::Shamari Smith

        participant_relationship  \
464                          NaN
1004                         NaN
8427                         NaN
11780                        NaN
14054                        NaN
...                          ...
216318                       NaN
218072                       NaN
221829                       NaN
222739                       NaN
225266                       NaN

                                       participant_status  \
464                               0::Injured||1::Unharmed
1004                0::Unharmed||1::Unharmed||2::Unharmed
8427    0:Injured|1:Unharmed|2:Unharmed|3:Unharmed|4:U...
11780                                          0::Injured
14054                                                 NaN
...                                                   ...
216318                              0::Unharmed, Arrested
218072                                                NaN
221829  0::Unharmed, Arrested||1::Unharmed, Arrested||...
222739                            0::Injured||1::Unharmed
225266                              0::Unharmed, Arrested

                                         participant_type  \
464                         0::Victim||1::Subject-Suspect
1004    0::Victim||1::Subject-Suspect||2::Subject-Suspect
8427    0:Victim|1:Subject-Suspect|2:Subject-Suspect|3...
11780                                           0::Victim
14054                                                 NaN
...                                                   ...
216318                                 0::Subject-Suspect
218072                                                NaN
221829  0::Subject-Suspect||1::Subject-Suspect||2::Sub...
222739                      0::Victim||1::Subject-Suspect
225266                                 0::Subject-Suspect

                                                  sources  \
464     http://thegazette.com/2014/01/06/iowa-city-pol...
1004    http://thegazette.com/2014/01/06/attempted-rob...
8427    http://thegazette.com/2014/03/16/iowa-city-sho...
11780   http://thegazette.com/2014/03/09/iowa-city-pol...
14054   http://www.kcrg.com/news/crime/Iowa-City-Polic...
...                                                   ...
216318  http://www.thegazette.com/subject/news/public-...
218072  http://www.kcrg.com/content/news/University-of...
221829  http://www.thegazette.com/subject/news/public-...
222739  http://whotv.com/2017/12/11/iowa-dnr-three-peo...
225266  http://www.kwwl.com/story/37146795/2017/12/27/...

       state_house_district state_senate_district
464                    85.0                  43.0
1004                   86.0                  43.0
8427                   74.0                  37.0
11780                  74.0                  37.0
14054                  74.0                  37.0
...                     ...                   ...
216318                  NaN                   NaN
218072                 85.0                  43.0
221829                  NaN                   NaN
222739                 73.0                  37.0
225266                 86.0                  43.0

[67 rows x 29 columns]

#### 1C. Filter the original data frame to show incidents that occurred in both Iowa City (like step b) and Cedar Rapids, IA. Be sure not to include Cedar Rapids, NE.  Save results to a new data frame named corridor_ia. How many incidents occurred in Iowa City and Cedar Rapids, IA? Show the new data frame.

In [5]:
# create new dataframe called corridor_ia and include Cedar Rapids, IA

corridor_ia = df[((df['city_or_county'] == 'Iowa City') & (df['state'] == 'Iowa')) | ((df['city_or_county'] == 'Cedar Rapids') & (df['state'] == 'Iowa'))]

print(f"Incidents in Iowa City and Cedar Rapids, IA: {len(corridor_ia)}\n")

print(corridor_ia)

Incidents in Iowa City and Cedar Rapids, IA: 306

        incident_id        date state city_or_county  \
464           93491  2014-01-01  Iowa      Iowa City
728           92650  2014-01-03  Iowa   Cedar Rapids
1004          93495  2014-01-05  Iowa      Iowa City
2156          96324  2014-01-14  Iowa   Cedar Rapids
4518         200320  2014-01-30  Iowa   Cedar Rapids
...             ...         ...   ...            ...
230278      1037698  2018-01-28  Iowa   Cedar Rapids
232186      1055136  2018-02-10  Iowa   Cedar Rapids
237180      1071075  2018-03-15  Iowa   Cedar Rapids
237794      1073486  2018-03-19  Iowa   Cedar Rapids
238738      1077808  2018-03-25  Iowa   Cedar Rapids

                         address  n_killed  n_injured  \
464     backseat of victim's car         0          1
728         5620 Johnson Ave. NW         0          1
1004                1416 Plum St         0          0
2156     4000 block of Wilson Av         0          0
4518         3515 Banar Drive SW         3          0
...                          ...       ...        ...
230278             217 3rd St SE         0          1
232186                       NaN         0          1
237180       2125 Westdale Dr SW         0          1
237794            639 40th St SE         1          1
238738              3000 J St SW         0          0

                                             incident_url  \
464      http://www.gunviolencearchive.org/incident/93491
728      http://www.gunviolencearchive.org/incident/92650
1004     http://www.gunviolencearchive.org/incident/93495
2156     http://www.gunviolencearchive.org/incident/96324
4518    http://www.gunviolencearchive.org/incident/200320
...                                                   ...
230278  http://www.gunviolencearchive.org/incident/103...
232186  http://www.gunviolencearchive.org/incident/105...
237180  http://www.gunviolencearchive.org/incident/107...
237794  http://www.gunviolencearchive.org/incident/107...
238738  http://www.gunviolencearchive.org/incident/107...

                                               source_url  \
464     http://thegazette.com/2014/01/06/iowa-city-pol...
728     http://thegazette.com/2014/01/08/teen-charged-...
1004    http://thegazette.com/2014/01/06/attempted-rob...
2156    http://www.kcrg.com/news/crime/Cedar-Rapids-Po...
4518    http://www.kwwl.com/story/24588260/2014/01/30/...
...                                                   ...
230278  http://www.kcrg.com/content/news/Man-wanted-fo...
232186  http://www.thegazette.com/subject/news/public-...
237180  http://www.thegazette.com/subject/news/public-...
237794  http://cbs2iowa.com/news/local/names-released-...
238738  http://www.kwwl.com/story/37804757/2018/03/Sun...

        incident_url_fields_missing  ...      participant_age  \
464                           False  ...                1::35
728                           False  ...         0::21||1::19
1004                          False  ...                  NaN
2156                          False  ...                0::20
4518                          False  ...  0::41||1::73||2::47
...                             ...  ...                  ...
230278                        False  ...         0::23||1::21
232186                        False  ...                  NaN
237180                        False  ...         0::32||1::28
237794                        False  ...         0::35||1::30
238738                        False  ...                  NaN

                           participant_age_group  \
464                   0::Adult 18+||1::Adult 18+
728                   0::Adult 18+||1::Adult 18+
1004    0::Adult 18+||1::Adult 18+||2::Adult 18+
2156    0::Adult 18+||1::Adult 18+||2::Adult 18+
4518    0::Adult 18+||1::Adult 18+||2::Adult 18+
...                                          ...
230278                0::Adult 18+||1::Adult 18+
232186  0::Adult 18+||1::Adult 18+||2::Adult 18+
237180                0::Adult 18+||1::Adult 18+
237794                0::Adult 18+||1::Adult 18+
238738                                       NaN

                   participant_gender  \
464              0::Female||1::Female
728                0::Male||1::Female
1004      0::Female||1::Male||2::Male
2156        0::Male||1::Male||2::Male
4518    0::Female||1::Female||2::Male
...                               ...
230278               0::Male||1::Male
232186             0::Female||1::Male
237180               0::Male||1::Male
237794               0::Male||1::Male
238738                            NaN

                                         participant_name  \
464                                1::Laticia T. Robinson
728              0::Garret Chmelicek||1::Mariah L. Sprous
1004                                                  NaN
2156                                                  NaN
4518    0::Ingrid Huber Livingston||1::Linda Jane Hube...
...                                                   ...
230278                0::Michael Hodges||1::Zevon Johnson
232186                                    2::Gage F Skola
237180                0::Isaac Chatman||1::Kent T Stevens
237794           0::Brandon Toepfer||1::Kristopher Booker
238738                                                NaN

        participant_relationship                           participant_status  \
464                          NaN                      0::Injured||1::Unharmed
728                          NaN                      0::Injured||1::Unharmed
1004                         NaN        0::Unharmed||1::Unharmed||2::Unharmed
2156                         NaN        0::Unharmed||1::Unharmed||2::Unharmed
4518                         NaN              0::Killed||1::Killed||2::Killed
...                          ...                                          ...
230278                       NaN  0::Injured, Arrested||1::Unharmed, Arrested
232186                       NaN                      0::Injured||1::Unharmed
237180                       NaN            0::Injured||1::Unharmed, Arrested
237794                       NaN                        0::Injured||1::Killed
238738                       NaN                                          NaN

                                         participant_type  \
464                         0::Victim||1::Subject-Suspect
728                         0::Victim||1::Subject-Suspect
1004    0::Victim||1::Subject-Suspect||2::Subject-Suspect
2156    0::Victim||1::Subject-Suspect||2::Subject-Suspect
4518             0::Victim||1::Victim||2::Subject-Suspect
...                                                   ...
230278                      0::Victim||1::Subject-Suspect
232186           0::Victim||1::Victim||2::Subject-Suspect
237180                      0::Victim||1::Subject-Suspect
237794                      0::Victim||1::Subject-Suspect
238738                                                NaN

                                                  sources  \
464     http://thegazette.com/2014/01/06/iowa-city-pol...
728     http://thegazette.com/2014/01/03/overnight-sho...
1004    http://thegazette.com/2014/01/06/attempted-rob...
2156    http://www.kcrg.com/news/crime/Cedar-Rapids-Po...
4518    http://www.kwwl.com/story/24588260/2014/01/30/...
...                                                   ...
230278  http://www.thegazette.com/subject/news/public-...
232186  http://www.thegazette.com/subject/news/public-...
237180  http://www.thegazette.com/subject/news/public-...
237794  http://www.kcrg.com/content/news/Authorities-r...
238738  http://www.kwwl.com/story/37804757/2018/03/Sun...

       state_house_district state_senate_district
464                    85.0                  43.0
728                    70.0                  35.0
1004                   86.0                  43.0
2156                   69.0                  35.0
4518                   69.0                  35.0
...                     ...                   ...
230278                 69.0                  35.0
232186                 65.0                  33.0
237180                 69.0                  35.0
237794                 65.0                  33.0
238738                 65.0                  33.0

[306 rows x 29 columns]

#### 1D. Save all Iowa incidents into a new data frame named iowa_df and save it as a JSON file named iowa_incidents.json. Verify the created JSON file is valid using https://jsonlint.com.

In [15]:
# create new iowa_df dataframe and filter to all Iowa incidents

iowa_df = df[(df['state'] == 'Iowa')]

# create JSON file named iowa_incidents.json

iowa_df.to_json('iowa_incidents.json', orient='records', lines=False)

print(f'Incidents in Iowa: {len(iowa_df)}')

Incidents in Iowa: 2517

#### 1E. In 2016, which cities and states had the most fatalities? Display the maximum number killed in 2016. Show n_killed, city_or_county, and state columns for records that match the maximum number killed.

In [16]:
# convert date column to datetime from an object

df['date'] = pd.to_datetime(df['date'])

# extract year from datetime format

incidents_2016 = df[df['date'].dt.year == 2016]

# get the sum of all values

aggregated_2016 = incidents_2016.groupby(['city_or_county', 'state'], as_index=False)['n_killed'].sum()

# find the maximum of the values 

max_killed_2016 = aggregated_2016['n_killed'].max()

print(f'max fatalities 2016: {max_killed_2016}')

print('-'*20)

max_killed_records = aggregated_2016[aggregated_2016['n_killed'] == max_killed_2016]

display(max_killed_records[['n_killed', 'city_or_county', 'state']])

max fatalities 2016: 591
--------------------

      n_killed city_or_county     state
1303       591        Chicago  Illinois

## Problem 2

#### Load the FIFA 21 complete player data set (players_21.csv) into a data frame named fifa_21.

In [22]:
# read data into data frame

fifa_21 = pd.read_csv('players_21.csv', encoding='utf-8', sep=',')

#### 2A. Subset the following player IDs (sofifa_id) into a separate data frame named selected_players. Save only the player id and long name fields into this new data frame.

In [29]:
# select the 6 player ids and make a list

player_ids = [231747, 153079, 162835, 200104, 223848, 208421]

# make sure only the sofifa_id and long name fields are printed

selected_players = fifa_21[fifa_21['sofifa_id'].isin(player_ids)][['sofifa_id', 'long_name']]

print(selected_players)

     sofifa_id                          long_name
6       231747               Kylian Mbappé Lottin
13      153079  Sergio Leonel Agüero del Castillo
23      162835                   Samir Handanovič
46      200104                            손흥민 孙兴慜
70      223848            Sergej Milinković-Savić
112     208421               Saúl Ñíguez Esclápez

#### 2B. Subset players with a height greater than or equal to 191cm and a weight greater than or equal to 90kg into a separate data frame named big_players. Display the number of players in this new data frame.

In [30]:
# subset players with height and weight

big_players = fifa_21[(fifa_21['height_cm'] >= 191) & (fifa_21['weight_kg'] >= 90)]

print(f"There are {len(big_players)} players who meet the criteria.")

There are 355 players who meet the criteria.

#### 2C. What is the age of the oldest player(s)? The youngest? What is the median age and the mean age of all players. Store each in variables and display them. Display results in whole numbers.

In [32]:
# find the youngest age in the dataset

youngest_players = fifa_21['age'].min()

# find the median age and round it to a whole number

median_age = round(fifa_21['age'].median())

#find the mean age and round to a whole number 
mean_age = round(fifa_21['age'].mean())

# find the oldest age in the dataset

oldest_players = fifa_21['age'].max()

print('Youngest player(s):', youngest_players)

print('Median player age:', median_age)

print('Mean player age:', mean_age)

print('Oldest player(s):', oldest_players)

Youngest player(s): 16
Median player age: 25
Mean player age: 25
Oldest player(s): 53

#### 2D. Show the long name, age, and height for the oldest player(s) who prefer their left foot.

In [34]:
# find the oldest player that prefers their left foot

left_foot_player = fifa_21[fifa_21['preferred_foot'] == 'Left']['age'].max()

# use & to make sure that the long name, age and height are included 

left_foot_player = fifa_21[(fifa_21['preferred_foot'] == 'Left') & (fifa_21['age'] == left_foot_player)][['long_name', 'age', 'height_cm']]

display(left_foot_player)

                                long_name  age  height_cm
11701  Hussein Omar Abdul Ghani Sulaimani   43        173

#### 2E. Display the number of athletes and the number of columns in this data set

In [13]:
# use .nunique() to find the number of distinct values for sofifa_id column

athletes = fifa_21['sofifa_id'].nunique()

# use len(fifa_21.columns) to find the number of variables (columns) in the data set

variables = len(fifa_21.columns)

print('Athletes:', athletes)

print('Variables:', variables)

Athletes: 18944
Variables: 106